<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RandomEvent;

class RandomEventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $events = [
            [
                'title' => 'Lucky Drop',
                'description' => 'Fortune smiles upon a chosen player...',
                'effect' => 'One random player: +5 XP. A small reward is granted instantly.',
                'xp_reward' => 5,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'positive',
                'sort_order' => 1,
            ],
            [
                'title' => 'Double XP',
                'description' => 'Energy surges through your actions...',
                'effect' => 'All players: Next task gives x2 XP. Applies only to the next activity.',
                'xp_reward' => 0,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 2,
            ],
            [
                'title' => 'System Glitch',
                'description' => 'The system malfunctions unexpectedly...',
                'effect' => 'All players: -3 XP OR answer 1 question. Answer correctly to cancel the penalty.',
                'xp_reward' => 0,
                'xp_penalty' => 3,
                'target_type' => 'all',
                'event_type' => 'negative',
                'sort_order' => 3,
            ],
            [
                'title' => 'Boss Question',
                'description' => 'A powerful challenge appears...',
                'effect' => 'One random player: +10 XP if correct. No reward if unanswered.',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 4,
            ],
            [
                'title' => 'Team Power',
                'description' => 'Strength lies in unity...',
                'effect' => 'All players pair up: +7 XP each. Both must complete the task.',
                'xp_reward' => 7,
                'xp_penalty' => 0,
                'target_type' => 'pair',
                'event_type' => 'positive',
                'sort_order' => 5,
            ],
            [
                'title' => 'Risk or Reward',
                'description' => 'Will you play safe or risk it all?',
                'effect' => 'Choose your fate: Safe: +3 XP, Risk: +10 XP or 0 XP',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 6,
            ],
            [
                'title' => 'Double Trouble',
                'description' => 'The challenge grows stronger...',
                'effect' => 'All players: Harder task = +15 XP. Only for those who complete it.',
                'xp_reward' => 15,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'challenge',
                'sort_order' => 7,
            ],
            [
                'title' => 'Pop Quiz Raid',
                'description' => 'A sudden test strikes the class...',
                'effect' => 'All players: +5 XP if correct. Stay alert at all times.',
                'xp_reward' => 5,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'challenge',
                'sort_order' => 8,
            ],
            [
                'title' => 'Shield Activated',
                'description' => 'A protective force surrounds you...',
                'effect' => 'All players: No XP loss next task. You are safe from penalties.',
                'xp_reward' => 0,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 9,
            ],
            [
                'title' => 'Creative Burst',
                'description' => 'Your imagination takes control...',
                'effect' => 'All players: +8 XP for creative output. Show your unique ideas.',
                'xp_reward' => 8,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 10,
            ],
            [
                'title' => 'Duel Mode',
                'description' => 'Two challengers step forward...',
                'effect' => 'Two players compete: Winner: +10 XP | Loser: +3 XP',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'pair',
                'event_type' => 'challenge',
                'sort_order' => 11,
            ],
            [
                'title' => 'Speak Up',
                'description' => 'Your voice becomes your power...',
                'effect' => 'One player explains a concept: +7 XP. Clarity earns the reward.',
                'xp_reward' => 7,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 12,
            ],
            [
                'title' => 'Puzzle Break',
                'description' => 'A challenge of the mind appears...',
                'effect' => 'All players: Solve puzzle = +8 XP. Think carefully.',
                'xp_reward' => 8,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'challenge',
                'sort_order' => 13,
            ],
            [
                'title' => 'Time Freeze',
                'description' => 'Time slows down for a moment...',
                'effect' => 'All players: +3 minutes. Use it wisely.',
                'xp_reward' => 0,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 14,
            ],
            [
                'title' => 'Hero Moment',
                'description' => 'A chance to help others arises...',
                'effect' => 'Help a classmate: +6 XP. Kindness is rewarded.',
                'xp_reward' => 6,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'positive',
                'sort_order' => 15,
            ],
            [
                'title' => 'Mystery Box',
                'description' => 'The unknown awaits inside...',
                'effect' => 'One player receives: +5 XP, +10 XP, or a mini-task',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'neutral',
                'sort_order' => 16,
            ],
            [
                'title' => 'Task Swap',
                'description' => 'Walk in another\'s path...',
                'effect' => 'Swap tasks with a partner: +7 XP. Adapt and complete.',
                'xp_reward' => 7,
                'xp_penalty' => 0,
                'target_type' => 'pair',
                'event_type' => 'challenge',
                'sort_order' => 17,
            ],
            [
                'title' => 'Instant Boost',
                'description' => 'A sudden burst of power...',
                'effect' => 'One player: +10 XP instantly. No conditions needed.',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'positive',
                'sort_order' => 18,
            ],
            [
                'title' => 'Target Lock',
                'description' => 'All eyes on one player...',
                'effect' => 'Selected player: +10 XP if successful. Failure gives no reward.',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 19,
            ],
            [
                'title' => 'Hint Drop',
                'description' => 'A clue appears to guide you...',
                'effect' => 'All players: Easier task = +3 XP. Less reward, more help.',
                'xp_reward' => 3,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 20,
            ],
            [
                'title' => 'Roll Your Fate',
                'description' => 'Let chance decide your destiny...',
                'effect' => 'Roll the dice: 3 XP, 5 XP, or 10 XP',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'neutral',
                'sort_order' => 21,
            ],
            [
                'title' => 'Experiment Mode',
                'description' => 'Try something new...',
                'effect' => 'All players: +8 XP for new approach. Even imperfect attempts count.',
                'xp_reward' => 8,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 22,
            ],
            [
                'title' => 'Speed Run',
                'description' => 'Only the fastest will win...',
                'effect' => 'Fastest correct student: +10 XP. Accuracy still matters.',
                'xp_reward' => 10,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 23,
            ],
            [
                'title' => 'Role Play',
                'description' => 'Become the concept...',
                'effect' => 'Act it out: +8 XP. Learning through action.',
                'xp_reward' => 8,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 24,
            ],
            [
                'title' => 'Unlock Challenge',
                'description' => 'A locked problem awaits...',
                'effect' => 'Complete all steps: +12 XP. Solve it fully.',
                'xp_reward' => 12,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'challenge',
                'sort_order' => 25,
            ],
            [
                'title' => 'XP Tax',
                'description' => 'A price must be paid...',
                'effect' => 'All players: -3 XP OR complete a task. Avoid the penalty.',
                'xp_reward' => 0,
                'xp_penalty' => 3,
                'target_type' => 'all',
                'event_type' => 'negative',
                'sort_order' => 26,
            ],
            [
                'title' => 'Streak Booster',
                'description' => 'Consistency is rewarded...',
                'effect' => 'Players on streak: +5 XP. Keep it going.',
                'xp_reward' => 5,
                'xp_penalty' => 0,
                'target_type' => 'random',
                'event_type' => 'positive',
                'sort_order' => 27,
            ],
            [
                'title' => 'Freeze Check',
                'description' => 'The fastest becomes the guide...',
                'effect' => 'First finisher checks others: +5 XP. Help your classmates.',
                'xp_reward' => 5,
                'xp_penalty' => 0,
                'target_type' => 'single',
                'event_type' => 'positive',
                'sort_order' => 28,
            ],
            [
                'title' => 'Group Bonus',
                'description' => 'Victory as one...',
                'effect' => 'If majority succeeds: +5 XP all. Work together.',
                'xp_reward' => 5,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'positive',
                'sort_order' => 29,
            ],
            [
                'title' => 'Chaos Mode',
                'description' => 'Reality bends and rules change...',
                'effect' => 'Teacher changes rules this round. Adapt quickly to survive.',
                'xp_reward' => 0,
                'xp_penalty' => 0,
                'target_type' => 'all',
                'event_type' => 'neutral',
                'sort_order' => 30,
            ],
        ];

        foreach ($events as $event) {
            RandomEvent::create($event);
        }
    }
}
